blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

core/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace = 'blog')),
]

blog/models.py
from turtle import title
from django.db import models

class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from dataclasses import fields
from django import forms

from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, 'blog_list.html', context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {
            'form':form
        }
        return render(request, 'blog_create.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method=='POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
        context = {
            
        }
        return render(request, 'blog_create.html', context)

class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'post':post
        }
        return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

core/views.py
from multiprocessing import context
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {
            
        }
        return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="min-h-screen flex justify-center items-center bg-gray-200">
        <div class="flex flex-col items-center gap-10 bg-white p-12 rounded-2xl shadow-xl">
            <h1 class="text-center text-3xl font-black">Crea un post oe soplón</h1>
            <form method='POST' class="flex flex-col gap-4">
                {% csrf_token %}
                <p class="text-lg font-semibold">Título:</p>
                {{form.title}}
                <p class="text-lg font-semibold">Contenido:</p>
                {{form.content}}
                <button class="bg-indigo-600 text-white py-3 px-12 font-bold rounded-lg cursor-pointer hover:brightness-125 transition duration-200" type='submit'>Crear Post</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/blog_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="min-h-screen flex justify-center items-center bg-gray-200">
        <div class="flex flex-col items-center gap-10 bg-white p-12 rounded-2xl shadow-xl">
            <h1 class="text-center text-3xl font-black w-80">Estas seguro de eliminar tu post oe soplón</h1>
            <form method='POST' class="flex flex-col gap-4">
                {% csrf_token %}
                {{form}}<br>
                <button class="bg-indigo-600 text-white py-3 px-12 font-bold rounded-lg cursor-pointer hover:brightness-125 transition duration-200" type='submit'>Borrar Post</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="min-h-screen flex justify-center items-center bg-gray-200">
        <div class="flex flex-col items-start gap-5 bg-white p-12 rounded-2xl shadow-xl">
            <h1 class="text-xl font-black">{{post.title}}</h1>
            <p>{{post.content}}</p>
        </div>
    </div>
{% endblock content %}

templates/blog_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="py-28 px-80 bg-gray-200 h-full">
        <div class="flex justify-between items-center mb-8">
            <h1 class="text-4xl font-black">Posts Recientes</h1>
            <a class="bg-black text-white py-3 px-12 font-bold rounded-lg cursor-pointer hover:bg-indigo-600 transition duration-200" href={% url 'blog:create' %}>Crear Post</a>
        </div>
        <div class="flex flex-col gap-4">
            {% for post in posts %}
                <div class="flex justify-between items-center px-8 py-5 bg-white rounded-lg">
                    <a class="font-semibold" href={% url 'blog:detail' post.id %}>{{post.title}}</a>
                    <div class="flex gap-2 items-center">
                        <a class="bg-transparent text-indigo-600 border-2 border-indigo-600 py-1 px-3 font-semibold rounded-md cursor-pointer hover:text-white hover:bg-indigo-600 transition duration-200" href={% url 'blog:update' post.id %}>Editar</a>
                        <a class="bg-transparent text-red-500 border-2 border-red-500 py-1 px-3 font-semibold rounded-md cursor-pointer hover:text-white hover:bg-red-500 transition duration-200" href={% url 'blog:delete' post.id %}>Borrar</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/blog_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="min-h-screen flex justify-center items-center bg-gray-200">
        <div class="flex flex-col items-center gap-10 bg-white p-12 rounded-2xl shadow-xl">
            <h1 class="text-center text-3xl font-black">Edita tu post oe soplón</h1>
            <form method='POST' class="flex flex-col gap-4">
                {% csrf_token %}
                <p class="text-lg font-semibold">Título:</p>
                {{form.title}}
                <p class="text-lg font-semibold">Contenido:</p>
                {{form.content}}
                <button class="bg-indigo-600 text-white py-3 px-12 font-bold rounded-lg cursor-pointer hover:brightness-125 transition duration-200" type='submit'>Actualizar Post</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
   <div class="min-h-screen flex justify-center items-center bg-gray-200">
        <div class="flex flex-col items-center gap-10 bg-white p-12 rounded-2xl shadow-xl">
            <h1 class="text-center text-3xl font-black w-80">Bienvenido al primer blog de Nilson echo con Django y Tailwind</h1>
            <a class="bg-black text-white py-4 px-12 font-bold rounded-lg cursor-pointer hover:bg-indigo-600 transition duration-200" href={% url 'blog:home' %}>Continuar</a>
        </div>
   </div> 
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>